import {describe,it,expect} from 'vitest';
import {initialState,transition,validateSave,validParts,type GameState} from './engine';
import {FLOWERS} from './data';
import {canMove,colliders} from '../world/bridge';
const apply=(s:GameState,type:string,args={})=>transition(s,{type,...args},()=>.8);
const day=(s:GameState,rain=false)=>transition({...s,time:1200},{type:'sleep'},()=>rain?.1:.8).state;
describe('Complete farming and economy loop',()=>{
 for(const f of FLOWERS)it(`${f.id}: buy → plant → water daily → grow → harvest → sell`,()=>{let s=initialState();s=apply(s,'buy',{id:f.id}).state;expect(s.money).toBe(500-f.seed);s=apply(s,'plant',{id:f.id,index:0}).state;expect(s.inventory['seed:'+f.id]).toBe(0);for(let i=0;i<f.days;i++){s=apply(s,'water',{index:0}).state;s=day(s);}expect(s.farm[0].age).toBe(f.days);s=apply(s,'harvest',{index:0}).state;expect(s.inventory[f.id]).toBe(1);expect(s.farm[0].seed).toBeNull();s=apply(s,'sell',{id:f.id}).state;expect(s.money).toBe(500-f.seed+f.sell);expect(s.inventory[f.id]).toBe(0);expect(validateSave(s)).toBe(true);});
 it('rejects insufficient funds without mutation',()=>{const s={...initialState(),money:0};expect(apply(s,'buy',{id:'rose'})).toMatchObject({ok:false,state:s});});
 it('rejects missing seeds, occupied plots, premature and repeated harvests',()=>{let s=initialState();expect(apply(s,'plant',{id:'daisy',index:0}).ok).toBe(false);s=apply(s,'buy',{id:'daisy'}).state;s=apply(s,'plant',{id:'daisy',index:0}).state;expect(apply(s,'plant',{id:'daisy',index:0}).ok).toBe(false);expect(apply(s,'harvest',{index:0}).ok).toBe(false);expect(apply(s,'harvest',{index:99}).ok).toBe(false);});
 it('dry crops do not grow; watered crops grow once; rain waters new plants and next day',()=>{let s=initialState();s.inventory['seed:rose']=1;s=apply(s,'plant',{id:'rose',index:0}).state;s=day(s);expect(s.farm[0].age).toBe(0);s=apply(s,'water',{index:0}).state;expect(apply(s,'water',{index:0}).ok).toBe(false);s=day(s,true);expect(s.farm[0]).toMatchObject({age:1,watered:true});s.inventory['seed:daisy']=1;s=apply(s,'plant',{id:'daisy',index:1}).state;expect(s.farm[1].watered).toBe(true);s=day(s);expect(s.farm[0]).toMatchObject({age:2,watered:false});expect(s.farm[1].age).toBe(1);});
 it('keeps mature flowers ready without overflowing age',()=>{const s=initialState();s.farm[0]={seed:'daisy',age:2,watered:true};expect(day(s).farm[0].age).toBe(2);});
});
describe('Energy and time',()=>{
 it('blocks heavy actions at zero energy',()=>{const s=initialState();s.energy=0;s.inventory['seed:daisy']=1;for(const type of ['cast','plant'])expect(apply(s,type,{id:'daisy',index:0}).ok).toBe(false);});
 it('rest restores 20, clamps at max, and cannot be spammed',()=>{let s=initialState();s.energy=90;s=apply(s,'rest').state;expect(s.energy).toBe(100);expect(apply(s,'rest').ok).toBe(false);s.energy=20;s.time+=30;expect(apply(s,'rest').state.energy).toBe(40);});
 it('sleep only at night; midnight restores energy and advances day',()=>{let s=initialState();expect(apply(s,'sleep').ok).toBe(false);s.time=1439;s.energy=0;s=apply(s,'tick',{amount:2}).state;expect(s).toMatchObject({day:2,time:360,energy:100});});
 it('running costs one energy without going negative',()=>{const s=initialState();s.energy=1;const r=apply(s,'run');expect(r.state.energy).toBe(0);expect(apply(r.state,'run').ok).toBe(false);});
});
describe('Bouquets, orders and upgrades',()=>{
 it('accounts for duplicate flower selections atomically',()=>{let s=initialState();s.inventory.daisy=2;const result=apply(s,'bouquet',{flowers:['daisy','daisy','daisy']});expect(result.ok).toBe(false);expect(s.inventory.daisy).toBe(2);s.inventory.daisy=3;s=apply(s,'bouquet',{flowers:['daisy','daisy','daisy']}).state;expect(s.inventory.daisy).toBe(0);expect(s.bouquets[0].price).toBe(94);});
 it('customer pays sale price plus 50 once daily and requires matching flower',()=>{let s=initialState();s.inventory.daisy=3;s=apply(s,'bouquet',{flowers:['daisy','daisy','daisy']}).state;const id=s.bouquets[0].id;s.order.flower='rose';expect(apply(s,'order',{id}).ok).toBe(false);s.order.flower='daisy';s=apply(s,'order',{id}).state;expect(s.money).toBe(644);expect(s.order.fulfilled).toBe(true);expect(apply(s,'order',{id}).ok).toBe(false);expect(day(s).order.fulfilled).toBe(false);});
 it('normal bouquet sale removes the bouquet',()=>{let s=initialState();s.inventory.rose=3;s=apply(s,'bouquet',{flowers:['rose','rose','rose']}).state;s=apply(s,'sellBouquet',{id:s.bouquets[0].id}).state;expect(s.money).toBe(800);expect(s.bouquets.length).toBe(0);});
 it('charges for upgrades and enforces caps',()=>{let s=initialState();s.money=10000;s=apply(s,'upgradeFarm').state;expect(s.money).toBe(9600);expect(s.farm.length).toBe(20);expect(apply(s,'upgradeFarm').ok).toBe(false);for(let i=0;i<3;i++)s=apply(s,'upgradeEnergy').state;expect(s.maxEnergy).toBe(160);expect(s.money).toBe(7800);expect(apply(s,'upgradeEnergy').ok).toBe(false);for(let i=0;i<6;i++)s=apply(s,'decorate').state;expect(apply(s,'decorate').ok).toBe(false);expect(validateSave(s)).toBe(true);});
});
describe('Fishing and art',()=>{
 it('charges for a cast and adds all three fish rarities with correct sale prices',()=>{for(const [rng,id,price] of [[.1,'carp',40],[.8,'goldfish',60],[.98,'rare',150]] as const){let s=apply(initialState(),'cast').state;expect(s.energy).toBe(90);s=transition(s,{type:'catch'},()=>rng).state;expect(s.inventory[id]).toBe(1);s=apply(s,'sell',{id}).state;expect(s.money).toBe(500+price);}});
 it('saves painting and sculpture; charges energy; sells artwork exactly once',()=>{let s=initialState();s=apply(s,'art',{art:{kind:'painting',name:'Garden',image:'data:image/png;base64,AAAA'}}).state;expect(s.energy).toBe(85);const part={type:'cone',x:0,y:1,z:0,rx:0,ry:45,rz:0,scale:1,color:'#123456',material:'metal'};s=apply(s,'art',{art:{kind:'sculpture',name:'Cone',parts:[part]}}).state;expect(s.energy).toBe(70);expect(validateSave(s)).toBe(true);const id=s.artworks[1].id;s=apply(s,'sellArt',{id}).state;expect(s.money).toBe(595);expect(apply(s,'sellArt',{id}).ok).toBe(false);});
 it('rejects invalid and empty art without spending energy',()=>{const s=initialState();expect(apply(s,'art',{art:{kind:'sculpture',name:'Empty',parts:[]}}).ok).toBe(false);expect(apply(s,'art',{art:{kind:'painting',name:'bad',image:'javascript:alert(1)'}}).ok).toBe(false);expect(validParts([{x:NaN}])).toBe(false);});
});
describe('Persistence and collisions',()=>{
 it('round trips a save and rejects corrupted nested data',()=>{const s=initialState();expect(validateSave(JSON.parse(JSON.stringify(s)))).toBe(true);for(const invalid of [null,{}, {...s,energy:-1},{...s,inventory:{rose:1.5}},{...s,farm:[]},{...s,position:{x:Infinity,z:0,yaw:0}},{...s,maxEnergy:200}])expect(validateSave(invalid)).toBe(false);});
 it('blocks world boundary, water and important objects',()=>{colliders.length=0;colliders.push({x:5,z:5,w:2,d:2});expect(canMove(0,20)).toBe(true);expect(canMove(44,0)).toBe(false);expect(canMove(0,-31)).toBe(false);expect(canMove(5,5)).toBe(false);expect(canMove(7,5)).toBe(true);colliders.length=0;});
});

describe('Ready-made model painting',()=>{
 it('saves painted animals, restores colors, preserves old art, and sells once',()=>{let s=initialState();s=apply(s,'art',{art:{kind:'sculpture',name:'Earlier artwork',parts:[{type:'box',x:0,y:1,z:0,rx:0,ry:0,rz:0,scale:1,color:'#123456',material:'matte'}]}}).state;s=apply(s,'art',{art:{kind:'model',modelId:'cat',name:'Pink cat',colors:{'0':'#e78293','3':'#ab88c8'},image:'data:image/png;base64,AAAA'}}).state;expect(s.energy).toBe(70);expect(s.artworks).toHaveLength(2);const saved=JSON.parse(JSON.stringify(s));expect(validateSave(saved)).toBe(true);expect(saved.artworks[1].colors['0']).toBe('#e78293');const id=s.artworks[1].id;s=apply(s,'sellArt',{id}).state;expect(s.money).toBe(640);expect(s.artworks[0].kind).toBe('sculpture');expect(apply(s,'sellArt',{id}).ok).toBe(false);});
 it('rejects unknown models, empty paint, invalid colors and invalid region keys atomically',()=>{for(const art of [{kind:'model',modelId:'unknown',colors:{'0':'#ffffff'}},{kind:'model',modelId:'dog',colors:{}},{kind:'model',modelId:'rabbit',colors:{'0':'red'}},{kind:'model',modelId:'tortoise',colors:{'script':'#ffffff'}}]){const s=initialState(),r=apply(s,'art',{art:{...art,name:'Test'}});expect(r.ok).toBe(false);expect(r.state).toBe(s);}});
 it('supports each of the five selectable models',()=>{for(const modelId of ['cat','dog','rabbit','tortoise','guinea']){const r=apply(initialState(),'art',{art:{kind:'model',modelId,name:modelId,colors:{'0':'#ffffff'}}});expect(r.ok).toBe(true);expect(validateSave(r.state)).toBe(true);}});
});
