import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { ItemIcon } from './ItemIcon';
import { FISH } from '../game/data';
import { dispatch } from '../game/engine';
export function Fishing({ notify }: { notify: (s: string) => void }) {
    const [phase, setPhase] = useState<'idle' | 'waiting' | 'playing' | 'won' | 'lost'>('idle'), [sequence, setSequence] = useState<string[]>([]), [step, setStep] = useState(0), [time, setTime] = useState(100), [result, setResult] = useState(''); const status = useRef(phase), index = useRef(0); status.current = phase;
    const start = () => { const r = dispatch({ type: 'cast' }); notify(r.message); if (r.ok) { index.current = 0; setStep(0); setTime(100); setSequence(Array.from({ length: 7 }, () => Math.random() < .5 ? 'A' : 'D')); status.current = 'waiting'; setPhase('waiting'); } };
    useEffect(() => { if (phase !== 'waiting') return; const t = setTimeout(() => setPhase('playing'), 1800 + Math.random() * 2000); return () => clearTimeout(t); }, [phase]);
    useEffect(() => { if (phase !== 'playing') return; const start = performance.now(); const t = setInterval(() => { const left = Math.max(0, 100 - (performance.now() - start) / 140); setTime(left); if (left <= 0) { status.current = 'lost'; setPhase('lost'); } }, 60); return () => clearInterval(t); }, [phase]);
    const press = (key: string) => { if (status.current !== 'playing') return; if (sequence[index.current] !== key) { status.current = 'lost'; setPhase('lost'); return; } index.current++; setStep(index.current); if (index.current === sequence.length) { status.current = 'won'; const r = dispatch({ type: 'catch' }); setResult(r.message); notify(r.message); setPhase('won'); } };
    useEffect(() => { const fn = (e: KeyboardEvent) => { if (e.code === 'KeyA' || e.code === 'KeyD') { e.preventDefault(); if (!e.repeat) press(e.code === 'KeyA' ? 'A' : 'D'); } }; window.addEventListener('keydown', fn); return () => window.removeEventListener('keydown', fn); }, [sequence]);
    return <div className="fishing-game"><div className={'fish-illustration ' + (phase === 'waiting' ? 'bobbing' : '')}><ItemIcon id={phase === "won" ? (FISH.find(f => result.includes(f.name))?.id ?? "carp") : "goldfish"} size={110} /><span>≈ ≈ ≈ ≈ ≈</span></div><h3>{phase === 'idle' ? 'ช่วงเวลาเงียบ ๆ ริมทะเลสาบ' : phase === 'waiting' ? 'รอปลากินเหยื่อ…' : phase === 'playing' ? 'ปลาติดเบ็ดแล้ว!' : phase === 'won' ? result : 'ปลาว่ายหนีไปแล้ว'}</h3><p className="subtle">{phase === 'playing' ? 'กดตามลำดับ A / D ให้ครบก่อนหมดเวลา กดผิดปลาจะหนี' : phase === 'won' ? 'ปลาอยู่ในกระเป๋าแล้ว ฟินน์รับซื้ออยู่ฝั่งตะวันออก' : phase === 'waiting' ? 'มองผิวน้ำ แล้วรอจังหวะดี ๆ' : 'แต่ละครั้งใช้พลังงาน 10 หน่วย • ปลาหายากมีโอกาส 7%'}</p>{phase === 'playing' && <><div className="fish-time"><i style={{ width: time + '%' }} /></div><div className="sequence">{sequence.map((s, i) => <span key={i} className={i < step ? 'done' : i === step ? 'current' : ''}>{s}</span>)}</div><p>Fish HP {sequence.length - step} / {sequence.length}</p><div className="fish-buttons"><button onClick={() => press('A')}><ArrowLeft /> A</button><button onClick={() => press('D')}>D <ArrowRight /></button></div></>}{!['waiting', 'playing'].includes(phase) && <button onClick={start}>{phase === 'idle' ? 'หย่อนเบ็ด' : 'ตกปลาอีกครั้ง'} <span>−10 ⚡</span></button>}</div>;
}
